"""Installs the pre-commit PHI guard.

Owns: generating .git/hooks/pre-commit, which refuses any commit whose staged
content matches a patient identifier.

Does NOT own: the identifier list. That lives in data/phi_patterns.txt, which is
gitignored and generated by the pipeline from the patient demographics it parses.
Keeping the patterns out of this file is the point -- a committed script listing
real UHIDs would itself be the leak it is meant to prevent.

Run once after clone:  python tools/install_hooks.py
"""

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HOOK = REPO / ".git" / "hooks" / "pre-commit"
PATTERNS = REPO / "data" / "phi_patterns.txt"

# Written as a POSIX sh script: git runs hooks through sh even on Windows.
HOOK_BODY = r"""#!/bin/sh
# PHI guard. Generated by tools/install_hooks.py -- do not edit by hand.
#
# Refuses a commit if any staged file is a known PHI type, or if any staged
# content matches a patient identifier from data/phi_patterns.txt.

set -e
REPO_ROOT=$(git rev-parse --show-toplevel)
PATTERNS="$REPO_ROOT/data/phi_patterns.txt"
FAIL=0

# --- 1. Block PHI file types outright, even if force-added. ---
BAD_FILES=$(git diff --cached --name-only --diff-filter=ACM \
  | grep -Ei '\.(pdf|jpe?g|png|tiff?|webp|tsv|hocr)$|^data/|^dist/' || true)
if [ -n "$BAD_FILES" ]; then
  echo "BLOCKED: patient-data file types are staged:"
  echo "$BAD_FILES" | sed 's/^/  /'
  FAIL=1
fi

# --- 2. Block patient identifiers appearing in any staged content. ---
#
# `tr -d '\r'` is not optional: the patterns file is written on Windows and
# arrives CRLF, which leaves a trailing \r on every pattern and silently makes
# each regex match nothing. That failure mode is a guard that reports success
# while checking for identifiers that cannot exist -- worse than no guard.
#
# The loop runs inside a command substitution rather than a plain pipeline so
# its output reaches the parent shell; `FAIL=1` set inside a piped subshell
# would be discarded. Only filenames are echoed, never the identifier itself.
if [ -f "$PATTERNS" ]; then
  HITS=$(tr -d '\r' < "$PATTERNS" | while IFS= read -r pat; do
    case "$pat" in ''|'#'*) continue ;; esac
    git diff --cached --diff-filter=ACM -U0 -G"$pat" --name-only || true
  done | sort -u)
  if [ -n "$HITS" ]; then
    echo "BLOCKED: staged content matches a patient identifier:"
    echo "$HITS" | sed 's/^/  /'
    FAIL=1
  fi
else
  echo "WARNING: $PATTERNS missing -- identifier scan skipped."
fi

if [ "$FAIL" -ne 0 ]; then
  echo ""
  echo "Commit aborted. This repo never commits patient data."
  echo "Code and docs only. See .gitignore and docs/PROMPT.md."
  exit 1
fi
exit 0
"""


def main() -> int:
    if not (REPO / ".git").is_dir():
        print(f"No git repo at {REPO}", file=sys.stderr)
        return 1

    HOOK.parent.mkdir(parents=True, exist_ok=True)
    HOOK.write_text(HOOK_BODY, encoding="utf-8", newline="\n")
    HOOK.chmod(0o755)
    print(f"installed {HOOK}")

    if not PATTERNS.exists():
        print(f"NOTE: {PATTERNS} does not exist yet -- the identifier scan will")
        print("      be skipped until the pipeline generates it.")

    # Prove the repo actually ignores the data paths. A .gitignore that does not
    # match is worse than none, because it buys false confidence.
    for path in ("data/", "dist/"):
        r = subprocess.run(
            ["git", "-C", str(REPO), "check-ignore", "-q", path],
            capture_output=True,
        )
        state = "ignored" if r.returncode == 0 else "NOT IGNORED"
        print(f"  {path:8} {state}")
        if r.returncode != 0:
            print(f"FATAL: {path} is not ignored. Fix .gitignore before running the pipeline.")
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
