"""Install a pre-commit hook that runs the privacy checks and refuses on failure.

This exists because of a real mistake. The privacy check was run manually, it
FAILED, and the commit and push went ahead anyway -- because the commit did not
depend on the check's exit code. It turned out to be a false positive and
nothing real was exposed, but the process was wrong: a check whose result
nothing enforces is a suggestion.

    python tools/install_hooks.py

The hook runs tools/ci_privacy_check.py, which needs no secrets and works in any
clone. Maintainers holding the pattern denylist can additionally run
tools/scan_phi.py, which the hook invokes when that file is present.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HOOK = REPO / ".git" / "hooks" / "pre-commit"

BODY = r"""#!/bin/sh
# Privacy gate. Generated by tools/install_hooks.py -- do not edit by hand.
#
# Refuses the commit if the tree would publish patient data. Runs the
# no-secrets structural check always, and the full pattern scan when a denylist
# is available locally.

set -e
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

PY=python
command -v python >/dev/null 2>&1 || PY=python3

if ! "$PY" tools/ci_privacy_check.py; then
  echo ""
  echo "Commit aborted: the privacy check failed."
  echo "Fix the finding, or if it is a false positive, adjust the checker"
  echo "deliberately rather than bypassing it. See PRIVACY.md."
  exit 1
fi

DENY="$REPO_ROOT/data/public_denylist.json"
if [ -f "$DENY" ]; then
  if ! "$PY" tools/scan_phi.py . "$DENY"; then
    echo ""
    echo "Commit aborted: the pattern scan found publishable patient data."
    exit 1
  fi
fi

exit 0
"""


def main() -> int:
    if not (REPO / ".git").is_dir():
        print(f"no git repository at {REPO}", file=sys.stderr)
        return 1

    HOOK.parent.mkdir(parents=True, exist_ok=True)
    HOOK.write_text(BODY, encoding="utf-8", newline="\n")
    HOOK.chmod(0o755)
    print(f"installed {HOOK}")

    print("\nverifying it runs:")
    r = subprocess.run([sys.executable, "tools/ci_privacy_check.py"],
                       cwd=REPO, capture_output=True, text=True)
    print("  " + (r.stdout.strip().splitlines() or ["no output"])[-1])
    return 0 if r.returncode == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
